version: '3.8'

services:
  bookstore-ai:
    build: .
    container_name: bookstore-ai-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    volumes:
      # Volume para logs (opcional)
      - ./logs:/app/logs
      # Volume para dados (se quiser modificar books.json externamente)
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bookstore-network

  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: bookstore-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bookstore-ai
    restart: unless-stopped
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  bookstore-logs:
    driver: local